### PR TITLE
Sync with upstream changes

### PR DESCRIPTION
**Pull request by teutat3s**
Thank you for making this work on illumos!

Just a regular sync with the upstream repo, would be glad if this could get merged one day to keep this up to date.

If this is no longer maintained or of little interest we can abandon this PR.

### CODE REVIEW

**Comment by papertigers** [comment]
Hey, thanks for this!   Sorry it took me so long to notice. 
Are you still looking for me to merge this?

**Comment by teutat3s** [comment]
Hey @papertigers, no worries - thanks for taking a look!

I'd be happy if this could get merged, but I don't know if I broke something not so obvious when resolving the small merge conflicts.

EDIT: It builds fine and should be ready now.

**Comment by papertigers** [comment]
Let me try and set this up today in a test zone so I can confirm I can push bits through it and then I will click merge.

Thanks again!

**Comment by teutat3s** [comment]
Nice - thanks for testing it!

**Comment by teutat3s** [comment]
I did some tests in a SmartOS zone and bits are coming through fine here...
only after my recent commit. It seems some things did break with the merger and upstream changes.

Does it work for you as well? Looking forward for a review - when you have time.

**Pull request merged**
